after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 40
    inner.vertical =   40
    outer.left =       40
    outer.bottom =     40
    outer.top =        40
    outer.right =      40

[mode.main.binding]
    alt-r = 'layout tiles horizontal vertical'
    alt-a = 'layout accordion horizontal vertical'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-j             = 'workspace 1'
    alt-k             = 'workspace 2'
    alt-l             = 'workspace 3'
    alt-semicolon     = 'workspace 4'
    alt-m             = 'workspace 5'
    alt-comma         = 'workspace 6'
    alt-period        = 'workspace 7'
    alt-slash         = 'workspace 8'

    alt-cmd-j         = ['move-node-to-workspace 1', 'workspace 1']
    alt-cmd-k         = ['move-node-to-workspace 2', 'workspace 2']
    alt-cmd-l         = ['move-node-to-workspace 3', 'workspace 3']
    alt-cmd-semicolon = ['move-node-to-workspace 4', 'workspace 4']
    alt-cmd-m         = ['move-node-to-workspace 5', 'workspace 5']
    alt-cmd-comma     = ['move-node-to-workspace 6', 'workspace 6'] 
    alt-cmd-period    = ['move-node-to-workspace 7', 'workspace 7']
    alt-cmd-slash     = ['move-node-to-workspace 8', 'workspace 8']

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
