return {
    "folke/tokyonight.nvim",
    "rose-pine/neovim",
    "haishanh/night-owl.vim",
	"tanvirtin/monokai.nvim",
    "morhetz/gruvbox",
    "rebelot/kanagawa.nvim",
    "sainnhe/everforest",
    "catppuccin/nvim",
    "jdsimcoe/hyper.vim",
    "shaunsingh/nord.nvim",
    "whatyouhide/vim-gotham",
    "maxmx03/solarized.nvim",
    "blazkowolf/gruber-darker.nvim",
}
