[font]
builtin_box_drawing = true
size = 18
normal.family = "ibm plex mono"

[window]
dynamic_padding = true
opacity = 1#0.95
decorations = "Buttonless"
padding.x = 10
padding.y = 10

[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/theme.toml"]

